package dto;
// Generated 16-jun-2016 0:35:22 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private Integer idCita;
     private String fechaHora;
     private Integer idEstadoCita;
     private Integer idTecnico;
     private Integer idTecnologo;
     private Integer idPaciente;

    public Cita() {
    }

    public Cita(String fechaHora, Integer idEstadoCita, Integer idTecnico, Integer idTecnologo, Integer idPaciente) {
       this.fechaHora = fechaHora;
       this.idEstadoCita = idEstadoCita;
       this.idTecnico = idTecnico;
       this.idTecnologo = idTecnologo;
       this.idPaciente = idPaciente;
    }
   
    public Integer getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(Integer idCita) {
        this.idCita = idCita;
    }
    public String getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(String fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Integer getIdEstadoCita() {
        return this.idEstadoCita;
    }
    
    public void setIdEstadoCita(Integer idEstadoCita) {
        this.idEstadoCita = idEstadoCita;
    }
    public Integer getIdTecnico() {
        return this.idTecnico;
    }
    
    public void setIdTecnico(Integer idTecnico) {
        this.idTecnico = idTecnico;
    }
    public Integer getIdTecnologo() {
        return this.idTecnologo;
    }
    
    public void setIdTecnologo(Integer idTecnologo) {
        this.idTecnologo = idTecnologo;
    }
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }




}


