package modelo;
// Generated 28-may-2016 18:45:12 by Hibernate Tools 4.3.1



/**
 * DetallecitaId generated by hbm2java
 */
public class DetallecitaId  implements java.io.Serializable {


     private int idDetalleCita;
     private int idCita;

    public DetallecitaId() {
    }

    public DetallecitaId(int idDetalleCita, int idCita) {
       this.idDetalleCita = idDetalleCita;
       this.idCita = idCita;
    }
   
    public int getIdDetalleCita() {
        return this.idDetalleCita;
    }
    
    public void setIdDetalleCita(int idDetalleCita) {
        this.idDetalleCita = idDetalleCita;
    }
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallecitaId) ) return false;
		 DetallecitaId castOther = ( DetallecitaId ) other; 
         
		 return (this.getIdDetalleCita()==castOther.getIdDetalleCita())
 && (this.getIdCita()==castOther.getIdCita());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDetalleCita();
         result = 37 * result + this.getIdCita();
         return result;
   }   


}


