package modelo;
// Generated 28-may-2016 18:45:12 by Hibernate Tools 4.3.1



/**
 * Detallecita generated by hbm2java
 */
public class Detallecita  implements java.io.Serializable {


     private DetallecitaId id;
     private Cita cita;
     private Examen examen;
     private Resultado resultado;

    public Detallecita() {
    }

	
    public Detallecita(DetallecitaId id, Cita cita, Examen examen) {
        this.id = id;
        this.cita = cita;
        this.examen = examen;
    }
    public Detallecita(DetallecitaId id, Cita cita, Examen examen, Resultado resultado) {
       this.id = id;
       this.cita = cita;
       this.examen = examen;
       this.resultado = resultado;
    }
   
    public DetallecitaId getId() {
        return this.id;
    }
    
    public void setId(DetallecitaId id) {
        this.id = id;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Resultado getResultado() {
        return this.resultado;
    }
    
    public void setResultado(Resultado resultado) {
        this.resultado = resultado;
    }




}


