package modelo;
// Generated 28-may-2016 18:45:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private Integer idExamen;
     private Tipoexamen tipoexamen;
     private String nombreExam;
     private String rangoMin;
     private String rangoMax;
     private String unidad;
     private Set detallecitas = new HashSet(0);

    public Examen() {
    }

	
    public Examen(Tipoexamen tipoexamen) {
        this.tipoexamen = tipoexamen;
    }
    public Examen(Tipoexamen tipoexamen, String nombreExam, String rangoMin, String rangoMax, String unidad, Set detallecitas) {
       this.tipoexamen = tipoexamen;
       this.nombreExam = nombreExam;
       this.rangoMin = rangoMin;
       this.rangoMax = rangoMax;
       this.unidad = unidad;
       this.detallecitas = detallecitas;
    }
   
    public Integer getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(Integer idExamen) {
        this.idExamen = idExamen;
    }
    public Tipoexamen getTipoexamen() {
        return this.tipoexamen;
    }
    
    public void setTipoexamen(Tipoexamen tipoexamen) {
        this.tipoexamen = tipoexamen;
    }
    public String getNombreExam() {
        return this.nombreExam;
    }
    
    public void setNombreExam(String nombreExam) {
        this.nombreExam = nombreExam;
    }
    public String getRangoMin() {
        return this.rangoMin;
    }
    
    public void setRangoMin(String rangoMin) {
        this.rangoMin = rangoMin;
    }
    public String getRangoMax() {
        return this.rangoMax;
    }
    
    public void setRangoMax(String rangoMax) {
        this.rangoMax = rangoMax;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public Set getDetallecitas() {
        return this.detallecitas;
    }
    
    public void setDetallecitas(Set detallecitas) {
        this.detallecitas = detallecitas;
    }




}


