package modelo;
// Generated 28-may-2016 18:45:12 by Hibernate Tools 4.3.1



/**
 * MuestraId generated by hbm2java
 */
public class MuestraId  implements java.io.Serializable {


     private int idMuestra;
     private int idCita;

    public MuestraId() {
    }

    public MuestraId(int idMuestra, int idCita) {
       this.idMuestra = idMuestra;
       this.idCita = idCita;
    }
   
    public int getIdMuestra() {
        return this.idMuestra;
    }
    
    public void setIdMuestra(int idMuestra) {
        this.idMuestra = idMuestra;
    }
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MuestraId) ) return false;
		 MuestraId castOther = ( MuestraId ) other; 
         
		 return (this.getIdMuestra()==castOther.getIdMuestra())
 && (this.getIdCita()==castOther.getIdCita());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMuestra();
         result = 37 * result + this.getIdCita();
         return result;
   }   


}


