package modelo;
// Generated 28-may-2016 18:45:12 by Hibernate Tools 4.3.1



/**
 * Muestra generated by hbm2java
 */
public class Muestra  implements java.io.Serializable {


     private MuestraId id;
     private Cita cita;
     private Trabajador trabajador;
     private String estado;

    public Muestra() {
    }

	
    public Muestra(MuestraId id, Cita cita) {
        this.id = id;
        this.cita = cita;
    }
    public Muestra(MuestraId id, Cita cita, Trabajador trabajador, String estado) {
       this.id = id;
       this.cita = cita;
       this.trabajador = trabajador;
       this.estado = estado;
    }
   
    public MuestraId getId() {
        return this.id;
    }
    
    public void setId(MuestraId id) {
        this.id = id;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


