package modelo;
// Generated 28-may-2016 18:45:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer dni;
     private String nombre;
     private String apellidos;
     private String sexo;
     private int edad;
     private String telefono;
     private String correo;
     private String contrasenia;
     private Set citas = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(int edad) {
        this.edad = edad;
    }
    public Paciente(String nombre, String apellidos, String sexo, int edad, String telefono, String correo, String contrasenia, Set citas) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.sexo = sexo;
       this.edad = edad;
       this.telefono = telefono;
       this.correo = correo;
       this.contrasenia = contrasenia;
       this.citas = citas;
    }
   
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


