package modelo;
// Generated 28-may-2016 18:45:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Resultado generated by hbm2java
 */
public class Resultado  implements java.io.Serializable {


     private Integer idResultado;
     private Date fechaResultado;
     private String valor;
     private Set detallecitas = new HashSet(0);

    public Resultado() {
    }

    public Resultado(Date fechaResultado, String valor, Set detallecitas) {
       this.fechaResultado = fechaResultado;
       this.valor = valor;
       this.detallecitas = detallecitas;
    }
   
    public Integer getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(Integer idResultado) {
        this.idResultado = idResultado;
    }
    public Date getFechaResultado() {
        return this.fechaResultado;
    }
    
    public void setFechaResultado(Date fechaResultado) {
        this.fechaResultado = fechaResultado;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Set getDetallecitas() {
        return this.detallecitas;
    }
    
    public void setDetallecitas(Set detallecitas) {
        this.detallecitas = detallecitas;
    }




}


