package modelo;
// Generated 28-may-2016 18:45:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoexamen generated by hbm2java
 */
public class Tipoexamen  implements java.io.Serializable {


     private Integer idTipoExamen;
     private String nombre;
     private String colorTubo;
     private Set examens = new HashSet(0);

    public Tipoexamen() {
    }

    public Tipoexamen(String nombre, String colorTubo, Set examens) {
       this.nombre = nombre;
       this.colorTubo = colorTubo;
       this.examens = examens;
    }
   
    public Integer getIdTipoExamen() {
        return this.idTipoExamen;
    }
    
    public void setIdTipoExamen(Integer idTipoExamen) {
        this.idTipoExamen = idTipoExamen;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getColorTubo() {
        return this.colorTubo;
    }
    
    public void setColorTubo(String colorTubo) {
        this.colorTubo = colorTubo;
    }
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


