package modelo;
// Generated 28-may-2016 18:45:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trabajador generated by hbm2java
 */
public class Trabajador  implements java.io.Serializable {


     private Integer idTrabajador;
     private Tipousuario tipousuario;
     private String dni;
     private String nombres;
     private String apellidos;
     private Date fechaNac;
     private String sexo;
     private String telefono;
     private String correo;
     private String contrasenia;
     private String login;
     private Set muestras = new HashSet(0);
     private Set citas = new HashSet(0);

    public Trabajador() {
    }

	
    public Trabajador(Tipousuario tipousuario, String dni, String nombres, String apellidos) {
        this.tipousuario = tipousuario;
        this.dni = dni;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Trabajador(Tipousuario tipousuario, String dni, String nombres, String apellidos, Date fechaNac, String sexo, String telefono, String correo, String contrasenia, String login, Set muestras, Set citas) {
       this.tipousuario = tipousuario;
       this.dni = dni;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.telefono = telefono;
       this.correo = correo;
       this.contrasenia = contrasenia;
       this.login = login;
       this.muestras = muestras;
       this.citas = citas;
    }
   
    public Integer getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(Integer idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public Set getMuestras() {
        return this.muestras;
    }
    
    public void setMuestras(Set muestras) {
        this.muestras = muestras;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


