package modelo;
// Generated 16-jun-2016 0:35:22 by Hibernate Tools 4.3.1



/**
 * Detallecita generated by hbm2java
 */
public class Detallecita  implements java.io.Serializable {


     private Integer idDetalleCita;
     private Integer idCita;
     private Integer idExamen;
     private Integer idResultado;

    public Detallecita() {
    }

    public Detallecita(Integer idCita, Integer idExamen, Integer idResultado) {
       this.idCita = idCita;
       this.idExamen = idExamen;
       this.idResultado = idResultado;
    }
   
    public Integer getIdDetalleCita() {
        return this.idDetalleCita;
    }
    
    public void setIdDetalleCita(Integer idDetalleCita) {
        this.idDetalleCita = idDetalleCita;
    }
    public Integer getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(Integer idCita) {
        this.idCita = idCita;
    }
    public Integer getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(Integer idExamen) {
        this.idExamen = idExamen;
    }
    public Integer getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(Integer idResultado) {
        this.idResultado = idResultado;
    }




}


