package modelo;
// Generated 16-jun-2016 0:35:22 by Hibernate Tools 4.3.1



/**
 * Estadocita generated by hbm2java
 */
public class Estadocita  implements java.io.Serializable {


     private Integer idEstadoCita;
     private String estado;

    public Estadocita() {
    }

    public Estadocita(String estado) {
       this.estado = estado;
    }
   
    public Integer getIdEstadoCita() {
        return this.idEstadoCita;
    }
    
    public void setIdEstadoCita(Integer idEstadoCita) {
        this.idEstadoCita = idEstadoCita;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


