package modelo;
// Generated 16-jun-2016 0:35:22 by Hibernate Tools 4.3.1



/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private Integer idExamen;
     private String nombre;
     private String rangoMin;
     private String rangoMax;
     private String unidad;
     private Integer idTipoExamen;

    public Examen() {
    }

    public Examen(String nombre, String rangoMin, String rangoMax, String unidad, Integer idTipoExamen) {
       this.nombre = nombre;
       this.rangoMin = rangoMin;
       this.rangoMax = rangoMax;
       this.unidad = unidad;
       this.idTipoExamen = idTipoExamen;
    }
   
    public Integer getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(Integer idExamen) {
        this.idExamen = idExamen;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRangoMin() {
        return this.rangoMin;
    }
    
    public void setRangoMin(String rangoMin) {
        this.rangoMin = rangoMin;
    }
    public String getRangoMax() {
        return this.rangoMax;
    }
    
    public void setRangoMax(String rangoMax) {
        this.rangoMax = rangoMax;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public Integer getIdTipoExamen() {
        return this.idTipoExamen;
    }
    
    public void setIdTipoExamen(Integer idTipoExamen) {
        this.idTipoExamen = idTipoExamen;
    }




}


