package modelo;
// Generated 16-jun-2016 0:35:22 by Hibernate Tools 4.3.1



/**
 * Tipoexamen generated by hbm2java
 */
public class Tipoexamen  implements java.io.Serializable {


     private Integer idTipoExamen;
     private String nombre;
     private String colorTubo;

    public Tipoexamen() {
    }

    public Tipoexamen(String nombre, String colorTubo) {
       this.nombre = nombre;
       this.colorTubo = colorTubo;
    }
   
    public Integer getIdTipoExamen() {
        return this.idTipoExamen;
    }
    
    public void setIdTipoExamen(Integer idTipoExamen) {
        this.idTipoExamen = idTipoExamen;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getColorTubo() {
        return this.colorTubo;
    }
    
    public void setColorTubo(String colorTubo) {
        this.colorTubo = colorTubo;
    }




}


