package modelo;
// Generated 16-jun-2016 0:35:22 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String login;
     private String clave;
     private Integer idTipoUsuario;
     private Integer idPaciente;
     private Integer idTrabajador;

    public Usuario() {
    }

    public Usuario(String login, String clave, Integer idTipoUsuario, Integer idPaciente, Integer idTrabajador) {
       this.login = login;
       this.clave = clave;
       this.idTipoUsuario = idTipoUsuario;
       this.idPaciente = idPaciente;
       this.idTrabajador = idTrabajador;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    public Integer getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(Integer idTrabajador) {
        this.idTrabajador = idTrabajador;
    }




}


